# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 97023fc485994873e2510a232050c3715108274f01c33e27945a1515724e583a264546c9ee5a00425939217fe77e4868b691e5cfb4ad7e7d87d9bb17a46a91dc

test:
  secret_key_base: e477ca7a4bc4a0c4ad857e6ff221097bd2e449dc8de5b2d57767c9ee0ddd89c6289486bc27bf7b853db1ad98e38de4a5891cc5e8562984e8924aef0c567695f7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
